feat: test backend persistence separately using helm

diff --git a/.github/workflows/pgsql_microk8s.yml b/.github/workflows/pgsql_microk8s.yml
--- a/.github/workflows/pgsql_microk8s.yml
+++ b/.github/workflows/pgsql_microk8s.yml
@@ -1,32 +1,34 @@
-name: couchbase
+name: microk8s
+# This builds, packages and tests pygluu-kubernetes
 on:
   push:
-    branches:
-      - master
-      - main
-      - 4.3
     paths:
-      - "helm/**"
-  pull_request:
+      - "pygluu/**"
+      - "tests/**"
+      - "setup.py"
     branches:
-      - master
-      - main
       - 4.3
-    paths:
-      - "helm/**"
   workflow_dispatch:
+
 jobs:
   build:
+    name: Test with Microk8s
     runs-on: ubuntu-latest
+    strategy:
+      max-parallel: 6
+      matrix:
+        python-version: [3.7]
+        gluu-version: ['"4.3.2_dev"']
+        test-cases: ["install", "helm-install"]
 
     steps:
     - name: Checkout code
-      uses: actions/checkout@v3
+      uses: actions/checkout@master
 
-    - name: Set up Python 3.7
+    - name: Set up Python ${{ matrix.python-version }}
       uses: actions/setup-python@v2.3.2
       with:
-        python-version: 3.7
+        python-version: ${{ matrix.python-version }}
 
     - name: Install dependencies
       run: |
@@ -35,6 +37,18 @@ jobs:
         sudo pip3 install setuptools --upgrade
         sudo pip3 install pyOpenSSL --upgrade
         sudo pip3 install requests --upgrade
+
+    - name: Lint with flake8
+      run: |
+        sudo pip3 install flake8
+        # stop the build if there are Python syntax errors or undefined names
+        sudo flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
+        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
+        sudo flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
+
+    - name: Build pygluu
+      run: |
+        sudo apt-get update
         sudo apt-get install build-essential
         sudo pip3 install shiv
         mkdir /home/runner/work/test
@@ -42,22 +56,8 @@ jobs:
         cd /home/runner/work/test/
         sudo make zipapp
 
-    - name: Install microk8s
-      run: |
-        sudo snap install microk8s --classic
-        sudo snap alias microk8s.kubectl kubectl
-        sudo microk8s.status --wait-ready
-        sudo microk8s.enable dns registry ingress
-
-
-    - name: Install helm
-      run: |
-        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
-        chmod 700 get_helm.sh
-        ./get_helm.sh
-        sudo helm version
-
     - name: Test 1 settings(LDAP)
+      id: test1_settings
       run: |
         default_iface=$(awk '$2 == 00000000 { print $1 }' /proc/net/route)
         ip=$(ip addr show dev "$default_iface" | awk '$1 == "inet" { sub("/.*", "", $2); print $2 }')
@@ -65,26 +65,14 @@ jobs:
         {
           "ACCEPT_GLUU_LICENSE": "Y",
           "TEST_ENVIRONMENT": "Y",
-          "GLUU_VERSION": "4.3",
+          "GLUU_VERSION": ${{ matrix.gluu-version }},
           "GLUU_UPGRADE_TARGET_VERSION": "",
           "NGINX_INGRESS_NAMESPACE": "ingress-nginx",
-          "GLUU_HELM_RELEASE_NAME": "cn",
+          "GLUU_HELM_RELEASE_NAME": "gluu",
           "NGINX_INGRESS_RELEASE_NAME": "ningress",
-          "INSTALL_GLUU_GATEWAY": "N",
-          "INSTALL_POSTGRES": "N",
+          "INSTALL_POSTGRES": "Y",
           "POSTGRES_NAMESPACE": "postgres",
-          "KONG_NAMESPACE": "gluu-gateway",
-          "GLUU_GATEWAY_UI_NAMESPACE": "gg-ui",
-          "KONG_PG_USER": "kong",
-          "KONG_PG_PASSWORD": "MUs6#@",
-          "GLUU_GATEWAY_UI_PG_USER": "konga",
-          "GLUU_GATEWAY_UI_PG_PASSWORD": "MUs6#@",
-          "KONG_DATABASE": "kong",
-          "GLUU_GATEWAY_UI_DATABASE": "konga",
-          "POSTGRES_REPLICAS": 3,
           "POSTGRES_URL": "postgres.postgres.svc.cluster.local",
-          "KONG_HELM_RELEASE_NAME": "kong",
-          "GLUU_GATEWAY_UI_HELM_RELEASE_NAME": "ggui",
           "USE_ISTIO": "N",
           "USE_ISTIO_INGRESS": "N",
           "MIGRATION_ENABLED": "N",
@@ -100,38 +88,37 @@ jobs:
           "AWS_LB_TYPE": "",
           "USE_ARN": "",
           "ARN_AWS_IAM": "",
-          "COUCHBASE_CLUSTER_FILE_OVERRIDE": "Y",
           "LB_ADD": "",
           "REDIS_URL": "",
           "REDIS_TYPE": "",
           "REDIS_PW": "",
           "REDIS_USE_SSL": "false",
           "DEPLOYMENT_ARCH": "microk8s",
-          "PERSISTENCE_BACKEND": "couchbase",
+          "PERSISTENCE_BACKEND": "pgsql",
           "INSTALL_JACKRABBIT": "Y",
           "JACKRABBIT_STORAGE_SIZE": "4Gi",
           "JACKRABBIT_URL": "http://jackrabbit:8080",
           "JACKRABBIT_ADMIN_ID": "admin",
           "JACKRABBIT_ADMIN_PASSWORD": "admin",
-          "JACKRABBIT_CLUSTER": "Y",
+          "JACKRABBIT_CLUSTER": "N",
           "JACKRABBIT_PG_USER": "jackrabbit",
           "JACKRABBIT_PG_PASSWORD": "jackrabbit",
           "JACKRABBIT_DATABASE": "jackrabbit",
           "INSTALL_COUCHBASE": "Y",
           "COUCHBASE_NAMESPACE": "cbns",
           "COUCHBASE_VOLUME_TYPE": "io1",
-          "COUCHBASE_CLUSTER_NAME": "cn",
-          "COUCHBASE_URL": "cn.cbns.svc.cluster.local",
+          "COUCHBASE_CLUSTER_NAME": "cbgluu",
+          "COUCHBASE_URL": "cbgluu.cbns.svc.cluster.local",
           "COUCHBASE_INDEX_NUM_REPLICA": "0",
-          "COUCHBASE_USER": "cn",
+          "COUCHBASE_USER": "gluu",
           "COUCHBASE_SUPERUSER": "admin",
-          "COUCHBASE_PASSWORD": "P@ssw0rd",
-          "COUCHBASE_SUPERUSER_PASSWORD": "P@ssw0rd",
+          "COUCHBASE_BUCKET_PREFIX": "test",
+          "COUCHBASE_PASSWORD": "nTB5#|",
+          "COUCHBASE_SUPERUSER_PASSWORD": "nTB5#2",
           "COUCHBASE_CRT": "",
           "COUCHBASE_CN": "Couchbase CN",
           "COUCHBASE_SUBJECT_ALT_NAME": "",
-          "COUCHBASE_BUCKET_PREFIX": "cn",
-          "GLUU_LDAP_MULTI_CLUSTER": "N",
+          "COUCHBASE_CLUSTER_FILE_OVERRIDE": "N",
           "COUCHBASE_USE_LOW_RESOURCES": "Y",
           "COUCHBASE_DATA_NODES": "",
           "COUCHBASE_QUERY_NODES": "",
@@ -183,12 +170,10 @@ jobs:
           "OXPASSPORT_REPLICAS": 1,
           "OXD_SERVER_REPLICAS": 1,
           "CASA_REPLICAS": 1,
-          "RADIUS_REPLICAS": 1,
           "ENABLE_OXTRUST_API": "N",
           "ENABLE_OXTRUST_TEST_MODE": "N",
           "ENABLE_CACHE_REFRESH": "N",
           "ENABLE_OXD": "Y",
-          "ENABLE_RADIUS": "Y",
           "ENABLE_OXPASSPORT": "Y",
           "ENABLE_OXSHIBBOLETH": "Y",
           "ENABLE_FIDO2": "Y",
@@ -198,20 +183,62 @@ jobs:
           "ENABLE_OXAUTH_KEY_ROTATE": "Y",
           "ENABLE_OXTRUST_API_BOOLEAN": "true",
           "ENABLE_OXTRUST_TEST_MODE_BOOLEAN": "false",
-          "ENABLE_RADIUS_BOOLEAN": "true",
           "ENABLE_OXPASSPORT_BOOLEAN": "true",
           "ENABLE_CASA_BOOLEAN": "true",
           "ENABLE_SAML_BOOLEAN": "true",
           "EDIT_IMAGE_NAMES_TAGS": "N",
           "CONFIRM_PARAMS": "Y",
+          "GLUU_LDAP_MULTI_CLUSTER": "N",
+          "GLUU_INSTALL_SQL": "N",
+          "GLUU_SQL_DB_DIALECT": "mysql",
+          "GLUU_SQL_DB_NAMESPACE": "sql",
+          "GLUU_SQL_DB_HOST": "gluu-postgresql.sql.svc.cluster.local",
+          "GLUU_SQL_DB_PORT": "3306",
+          "GLUU_SQL_DB_NAME": "gluu",
+          "GLUU_SQL_DB_USER": "gluu",
+          "GLUU_SQL_DB_PASSWORD": "Test1234#",
           "GLUU_SCIM_PROTECTION_MODE": "OAUTH",
           "NGINX_LEGACY": "N"
         }
-    
-    - name: Install Couchbase
+        EOF
+
+    - name: Install microk8s
       run: |
-        cd /home/runner/work/test/
-        wget ${{ secrets.cbpackage }}
-        sudo ./pygluu-kubernetes.pyz install-couchbase || { sudo rm -rf ./couchbase; sudo ./pygluu-kubernetes.pyz install-couchbase; }
-        COUCHBASE_IP=$(sudo microk8s.kubectl get po cbgluu-0000 -n cbns --template={{.status.podIP}})
-        cat settings.json | sed 's/"INSTALL_COUCHBASE": "Y"/"INSTALL_COUCHBASE": "N"/g' |  sed -s "s@cbgluu.cbns.svc.cluster.local@$COUCHBASE_IP@g" > tmpfile.py && mv tmpfile.py settings.json
+        sudo snap install microk8s --classic --channel=1.21
+        sudo snap alias microk8s.kubectl kubectl
+        sudo microk8s.status --wait-ready
+        sudo microk8s.enable dns registry ingress
+    
+    - name: Install Helm
+      run: |
+        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
+        chmod 700 get_helm.sh
+        ./get_helm.sh
+        sudo helm version
+
+    - name: PostGRE
+      run: |
+          cd /home/runner/work/test/
+          cat settings.json | sed 's/"INSTALL_COUCHBASE": "Y"/"INSTALL_COUCHBASE": "N"/g' |  sed -s "s@cbgluu.cbns.svc.cluster.local@$COUCHBASE_IP@g" > tmpfile.py && mv tmpfile.py settings.json
+          cat settings.json | sed 's/"GLUU_INSTALL_SQL": "N"/"GLUU_INSTALL_SQL": "Y"/g' > tmpfile.py && mv tmpfile.py settings.json
+          cat settings.json | sed 's/"GLUU_SQL_DB_DIALECT": "mysql"/"GLUU_SQL_DB_DIALECT": "pgsql"/g' > tmpfile.py && mv tmpfile.py settings.json
+          cat settings.json | sed 's/"PERSISTENCE_BACKEND": "pgsql"/"PERSISTENCE_BACKEND": "sql"/g' > tmpfile.py && mv tmpfile.py settings.json
+          touch sqlfile
+
+    - name: Test Pygluu kubernetes PostGRE
+      id: test_kubernetes_postgres
+      run: |
+          cd /home/runner/work/test/
+          INSTALL=TRUE
+          [[ -f sqlfile  && "${{ matrix.test-cases }}" == "install"  ]] && INSTALL=FALSE
+          [[ "$INSTALL" == "TRUE" ]] && sudo ./pygluu-kubernetes.pyz ${{ matrix.test-cases }}
+          sleep 30
+          sudo microk8s.kubectl get po -n cbns
+          sudo microk8s.kubectl get po -n gluu
+          cat /home/runner/work/test/settings.json
+          sudo kubectl -n gluu wait --for=condition=available --timeout=600s deploy/gluu-oxauth || sudo kubectl logs -l app=oxauth -c oxauth -n gluu || echo "Not Found"
+          sudo kubectl wait -n gluu --for=condition=ready pod --timeout=300s -l statefulset.kubernetes.io/pod-name=gluu-oxtrust-0 || sudo kubectl logs -l app=oxtrust -c oxtrust -n gluu || echo "Not Found"
+          sudo kubectl -n gluu wait --for=condition=available --timeout=300s deploy/gluu-oxpassport || sudo kubectl logs -l app=oxpassport -c oxpassport -n gluu || echo "Not Found"
+          sudo kubectl -n gluu wait --for=condition=available --timeout=300s deploy/gluu-casa || sudo kubectl logs -l app=casa -c casa -n gluu || echo "Not Found"
+          sudo kubectl -n gluu wait --for=condition=available --timeout=300s deploy/gluu-oxd-server || sudo kubectl logs -l app=oxd-server -c oxd-server -n gluu || echo "Not Found"
+          sudo kubectl wait -n gluu --for=condition=ready pod --timeout=300s -l statefulset.kubernetes.io/pod-name=gluu-oxshibboleth-0 || sudo kubectl logs -l app=oxshiboleth -c oxshiboleth -n gluu || echo "Not Found"
