fix: cherry committed from 4.3

diff --git a/.github/workflows/pgsql_microk8s.yml b/.github/workflows/pgsql_microk8s.yml
--- a/.github/workflows/pgsql_microk8s.yml
+++ b/.github/workflows/pgsql_microk8s.yml
@@ -1,25 +1,30 @@
-name: minikube
+name: microk8s
 # This builds, packages and tests pygluu-kubernetes
 on:
-  #push:
-  #  paths:
-  #    - "pygluu/**"
-  #    - "tests/**"
-  #    - "setup.py"
+  push:
+    paths:
+      - "pygluu/**"
+      - "tests/**"
+      - "setup.py"
+    branches:
+      - "4.4"
   workflow_dispatch:
+
 jobs:
   build:
-
+    name: Test with Microk8s
     runs-on: ubuntu-latest
     strategy:
-      max-parallel: 4
+      max-parallel: 6
       matrix:
         python-version: [3.7]
-        gluu-version: ['"4.4.0_dev"']
-        persistence-backends: ['"ldap"']
+        gluu-version: ['"4.4.1_dev"']
+        test-cases: ["install", "helm-install"]
+
     steps:
     - name: Checkout code
       uses: actions/checkout@master
+
     - name: Set up Python ${{ matrix.python-version }}
       uses: actions/setup-python@v2.3.2
       with:
@@ -32,8 +37,6 @@ jobs:
         sudo pip3 install setuptools --upgrade
         sudo pip3 install pyOpenSSL --upgrade
         sudo pip3 install requests --upgrade
-        sudo pip3 install cffi --upgrade
-        sudo python3 -m pip install cffi
 
     - name: Lint with flake8
       run: |
@@ -43,29 +46,21 @@ jobs:
         # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
         sudo flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
 
-    - name: Install pygluu
+    - name: Build pygluu
       run: |
+        sudo apt-get update
+        sudo apt-get install build-essential
+        sudo pip3 install shiv
         mkdir /home/runner/work/test
         cp -r ./* /home/runner/work/test/
         cd /home/runner/work/test/
-        sudo make install
-
-    - name: Install Minikube
-      id: minikube
-      uses: medyagh/setup-minikube@master
-
-    - name: Install Istio
-      run: |
-          curl -sL https://istio.io/downloadIstioctl | sh -
-          export PATH=$PATH:$HOME/.istioctl/bin
-          istioctl operator init
+        sudo make zipapp
 
     - name: Test 1 settings(LDAP)
       id: test1_settings
       run: |
-        minikube addons enable ingress
-        ip=$(minikube ip)
-        kubectl describe nodes
+        default_iface=$(awk '$2 == 00000000 { print $1 }' /proc/net/route)
+        ip=$(ip addr show dev "$default_iface" | awk '$1 == "inet" { sub("/.*", "", $2); print $2 }')
         cat <<EOF > /home/runner/work/test/settings.json
         {
           "ACCEPT_GLUU_LICENSE": "Y",
@@ -75,11 +70,12 @@ jobs:
           "NGINX_INGRESS_NAMESPACE": "ingress-nginx",
           "GLUU_HELM_RELEASE_NAME": "gluu",
           "NGINX_INGRESS_RELEASE_NAME": "ningress",
-          "INSTALL_POSTGRES": "N",
+          "INSTALL_POSTGRES": "Y",
           "POSTGRES_NAMESPACE": "postgres",
           "POSTGRES_URL": "postgres.postgres.svc.cluster.local",
-          "USE_ISTIO": "Y",
+          "USE_ISTIO": "N",
           "USE_ISTIO_INGRESS": "N",
+          "MIGRATION_ENABLED": "N",
           "ISTIO_SYSTEM_NAMESPACE": "istio-system",
           "NODES_IPS": [
             "$ip"
@@ -97,10 +93,9 @@ jobs:
           "REDIS_TYPE": "",
           "REDIS_PW": "",
           "REDIS_USE_SSL": "false",
-          "DEPLOYMENT_ARCH": "minikube",
-          "PERSISTENCE_BACKEND": ${{ matrix.persistence-backends }},
+          "DEPLOYMENT_ARCH": "microk8s",
+          "PERSISTENCE_BACKEND": "pgsql",
           "INSTALL_JACKRABBIT": "Y",
-          "MIGRATION_ENABLED": "N",
           "JACKRABBIT_STORAGE_SIZE": "4Gi",
           "JACKRABBIT_URL": "http://jackrabbit:8080",
           "JACKRABBIT_ADMIN_ID": "admin",
@@ -145,7 +140,7 @@ jobs:
           "DEPLOY_MULTI_CLUSTER": "N",
           "HYBRID_LDAP_HELD_DATA": "",
           "LDAP_JACKRABBIT_VOLUME": "",
-          "APP_VOLUME_TYPE": 2,
+          "APP_VOLUME_TYPE": 1,
           "LDAP_STATIC_VOLUME_ID": "",
           "LDAP_STATIC_DISK_URI": "",
           "GLUU_CACHE_TYPE": "NATIVE_PERSISTENCE",
@@ -169,22 +164,22 @@ jobs:
           "OXAUTH_REPLICAS": 1,
           "OXTRUST_REPLICAS": 1,
           "LDAP_REPLICAS": 1,
+          "FIDO2_REPLICAS": 1,
+          "SCIM_REPLICAS": 1,
           "OXSHIBBOLETH_REPLICAS": 1,
           "OXPASSPORT_REPLICAS": 1,
           "OXD_SERVER_REPLICAS": 1,
           "CASA_REPLICAS": 1,
-          "FIDO2_REPLICAS": 1,
-          "SCIM_REPLICAS": 1,
-          "OXAUTH_KEYS_LIFE": 48,
           "ENABLE_OXTRUST_API": "N",
-          "ENABLE_FIDO2": "Y",
-          "ENABLE_SCIM": "Y",
           "ENABLE_OXTRUST_TEST_MODE": "N",
           "ENABLE_CACHE_REFRESH": "N",
           "ENABLE_OXD": "Y",
           "ENABLE_OXPASSPORT": "Y",
           "ENABLE_OXSHIBBOLETH": "Y",
+          "ENABLE_FIDO2": "Y",
+          "ENABLE_SCIM": "Y",
           "ENABLE_CASA": "Y",
+          "OXAUTH_KEYS_LIFE": 48,
           "ENABLE_OXAUTH_KEY_ROTATE": "Y",
           "ENABLE_OXTRUST_API_BOOLEAN": "true",
           "ENABLE_OXTRUST_TEST_MODE_BOOLEAN": "false",
@@ -193,27 +188,57 @@ jobs:
           "ENABLE_SAML_BOOLEAN": "true",
           "EDIT_IMAGE_NAMES_TAGS": "N",
           "CONFIRM_PARAMS": "Y",
-          "GLUU_LDAP_MULTI_CLUSTER": "N"
+          "GLUU_LDAP_MULTI_CLUSTER": "N",
+          "GLUU_INSTALL_SQL": "N",
+          "GLUU_SQL_DB_DIALECT": "mysql",
+          "GLUU_SQL_DB_NAMESPACE": "sql",
+          "GLUU_SQL_DB_HOST": "gluu-postgresql.sql.svc.cluster.local",
+          "GLUU_SQL_DB_PORT": "3306",
+          "GLUU_SQL_DB_NAME": "gluu",
+          "GLUU_SQL_DB_USER": "gluu",
+          "GLUU_SQL_DB_PASSWORD": "Test1234#",
+          "GLUU_SCIM_PROTECTION_MODE": "OAUTH",
+          "NGINX_LEGACY": "N"
         }
         EOF
 
-    - name: Install Couchbase
-      if: ${{ matrix.persistence-backends == '"couchbase"' }}
+    - name: Install microk8s
+      run: |
+        sudo snap install microk8s --classic --channel=1.21
+        sudo snap alias microk8s.kubectl kubectl
+        sudo microk8s.status --wait-ready
+        sudo microk8s.enable dns registry ingress
+    
+    - name: Install Helm
+      run: |
+        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
+        chmod 700 get_helm.sh
+        ./get_helm.sh
+        sudo helm version
+
+    - name: PostGRE
       run: |
           cd /home/runner/work/test/
-          wget ${{ secrets.cbpackage }}
-          sudo ./pygluu-kubernetes.pyz install-couchbase
-          COUCHBASE_IP=$(kubectl get po cbgluu-0000 -n cbns --template={{.status.podIP}})
           cat settings.json | sed 's/"INSTALL_COUCHBASE": "Y"/"INSTALL_COUCHBASE": "N"/g' |  sed -s "s@cbgluu.cbns.svc.cluster.local@$COUCHBASE_IP@g" > tmpfile.py && mv tmpfile.py settings.json
+          cat settings.json | sed 's/"GLUU_INSTALL_SQL": "N"/"GLUU_INSTALL_SQL": "Y"/g' > tmpfile.py && mv tmpfile.py settings.json
+          cat settings.json | sed 's/"GLUU_SQL_DB_DIALECT": "mysql"/"GLUU_SQL_DB_DIALECT": "pgsql"/g' > tmpfile.py && mv tmpfile.py settings.json
+          cat settings.json | sed 's/"PERSISTENCE_BACKEND": "pgsql"/"PERSISTENCE_BACKEND": "sql"/g' > tmpfile.py && mv tmpfile.py settings.json
+          touch sqlfile
 
-
-
-    - name: Test Pygluu kubernetes
-      id: test_kubernetes
+    - name: Test Pygluu kubernetes PostGRE
+      id: test_kubernetes_postgres
       run: |
           cd /home/runner/work/test/
-          sudo pygluu-kubernetes install
+          INSTALL=TRUE
+          [[ -f sqlfile  && "${{ matrix.test-cases }}" == "install"  ]] && INSTALL=FALSE
+          [[ "$INSTALL" == "TRUE" ]] && sudo ./pygluu-kubernetes.pyz ${{ matrix.test-cases }}
+          sleep 30
+          sudo microk8s.kubectl get po -n cbns
+          sudo microk8s.kubectl get po -n gluu
           cat /home/runner/work/test/settings.json
-          kubectl get po -n gluu
-          kubectl get po -n cbns
-
+          sudo kubectl -n gluu wait --for=condition=available --timeout=600s deploy/gluu-oxauth || sudo kubectl logs -l app=oxauth -c oxauth -n gluu || echo "Not Found"
+          sudo kubectl wait -n gluu --for=condition=ready pod --timeout=300s -l statefulset.kubernetes.io/pod-name=gluu-oxtrust-0 || sudo kubectl logs -l app=oxtrust -c oxtrust -n gluu || echo "Not Found"
+          sudo kubectl -n gluu wait --for=condition=available --timeout=300s deploy/gluu-oxpassport || sudo kubectl logs -l app=oxpassport -c oxpassport -n gluu || echo "Not Found"
+          sudo kubectl -n gluu wait --for=condition=available --timeout=300s deploy/gluu-casa || sudo kubectl logs -l app=casa -c casa -n gluu || echo "Not Found"
+          sudo kubectl -n gluu wait --for=condition=available --timeout=300s deploy/gluu-oxd-server || sudo kubectl logs -l app=oxd-server -c oxd-server -n gluu || echo "Not Found"
+          sudo kubectl wait -n gluu --for=condition=ready pod --timeout=300s -l statefulset.kubernetes.io/pod-name=gluu-oxshibboleth-0 || sudo kubectl logs -l app=oxshiboleth -c oxshiboleth -n gluu || echo "Not Found"
